name: weatherwise
description: "Google Earth-style Event Explorer with NASA Weather Data"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.6

  # 3D Globe and Maps
  flutter_earth_globe: ^1.0.5
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^2.1.1

  # HTTP and API
  http: ^1.1.0
  dio: ^5.3.3

  # Data and Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  sqflite: ^2.3.0

  # State Management
  provider: ^6.1.1

  # UI Enhancements
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^2.7.0

  # Charts and Data Visualization
  fl_chart: ^0.64.0
  syncfusion_flutter_charts: ^23.1.44
  xml: ^6.3.0  # For parsing NASA XML responses

  # Date and Time
  intl: ^0.18.1

  # File Operations
  csv: ^5.0.2
  permission_handler: ^11.0.1

  # Animations
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # The image shows 'assets/fonts' and 'assets/images'
  assets:
    - assets/images/
    # The errors indicate these are in pubspec.yaml but not in your directory structure
    # I've commented them out to fix the build. Uncomment/add them back when you create the directories and files.
    # - assets/animations/
    # - assets/data/

  fonts:
    - family: GoogleSans
      fonts:
        # The file names in the image are GoogleSansCode-*.ttf, not GoogleSans-*.ttf
        # Also, the image shows a 'fonts' folder inside 'assets'
        - asset: assets/fonts/GoogleSansCode-Regular.ttf
        - asset: assets/fonts/GoogleSansCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSansCode-Bold.ttf
          weight: 700